exclude: |
  (?x)(
    ^EDAPT/|
    ^ESPM/|
    ^GBC\ OAuth\ 2.0/|
    ^Salesforce\ Package/
  )

repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=2000']
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
  - repo: local
    hooks:
      - id: format-xml
        name: Format XML
        language: python
        entry: python format_xml.py
        types: [xml]
        additional_dependencies: ['lxml==4.6.1']
