name: CI

on:
  push:
    branches:
      - 'Dev'
      - 'master'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Parse Tag
        id: parse_tag
        run: |
          echo "GITHUB_REF: ${GITHUB_REF}"

          if [[ "${GITHUB_REF}" == "refs/heads/Dev" ]]; then
            OEP_TAG=develop
          elif [[ "${GITHUB_REF}" == "refs/tags/master" ]]; then
            OEP_TAG=$( cat "SEED Benchmark/OEI/pom.xml"  | sed '2 s/xmlns=".*"//g' | xmllint --xpath "string(/project/version)" -)
          else
            echo "Unhandled GITHUB_REF (this shouldn't happen), exiting"
            exit 1
          fi

          echo ::set-output name=oep_tag::${OEP_TAG}
      -
        name: Build Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: seedplatform/oep:latest,seedplatform/oep:${{ steps.parse_tag.outputs.oep_tag }}
          context: 'SEED Benchmark'
          file: 'SEED Benchmark/Dockerfile'
